### ISSUE TITLE
[Feature Request] integrate redis similarity search into docarray

### ISSUE THREAD

**Issue by bwanglzu** [RedisAI/VectorSimilarity#205]
**Is your feature request related to a problem? Please describe.**

Hi everyone, thanks for your great work on adding HNSW to Redis. I'm Bo working at @jina-ai . We build tools for developers for vector similarity search. And we would like to integrate Redis as one of our storage option in [docarray](https://docarray.jina.ai/advanced/document-store/), i was wondering can we have some collaborations over that? 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DvirDukhan** [comment]
Hi @bwanglzu 
we would be happy to discuss it. please reach out to us at dvir@redis.com ed.sandoval@redis.com
Thanks

**Comment by bwanglzu** [comment]
hi @DvirDukhan sorry for the late reply, i think we already planned a meeting with Sandoval, it's on this Friday. I'll close this issue :)
