### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by kefahi** [RedisAI/VectorSimilarity#314]
**Describe the bug**
Unable to compile

**To Reproduce**
1. git clone https://github.com/RedisAI/VectorSimilarity
2. cd VectorSimilarity
3. make

**Expected behavior**
Compilation should succeed

**Screenshots**
![image](https://user-images.githubusercontent.com/2543377/209427586-23ea2814-eccf-4500-bb5b-8ded1c9cc8c4.png)

**Environment (please complete the following information):**
 - OS: Fedora 37
 - CPU model: AMD Ryzen 7 5800HS 
 - Master

**Additional context**
I got the exact issue when trying to compile on Alpine linux (x86).

**Comment by DvirDukhan** [comment]
@kefahi 
thanks for reporting
which GCC version do you use?

**Comment by kefahi** [comment]
On Fedora 37, I have : `gcc (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)`

On Alpine, I have  : `gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924`

I get same error on both OS environments.

**Comment by DvirDukhan** [comment]
@kefahi confirmed reproduction on a clean fedora 37 image (not on 38 BTW) 
you can remove the `-Wall` flag from `src/VecSim/spaces/CMakeLists.txt` and you are good to go

**Comment by kefahi** [comment]
Thank you, @DvirDukhan 
I just tried that, and I'm getting the same error when running `make clean; make build`
Should I initiate the compilation process differently?

**Comment by kefahi** [comment]
@DvirDukhan it worked.

Thanks!
