### ISSUE TITLE
Is VectorSimilarity Usable For C API?

### ISSUE THREAD

**Issue by RMichaelPickering** [RedisAI/VectorSimilarity#409]
As far as I can tell, documentation of how to actually use the VectorSimilarity C API from a client program is scarce, and it doesn't seem to be yet ready for this purpose. Can you please provide clarification on the roadmap for moving this to production? I'm ideally looking for support of RediSearch and vector similarity in C++ for production use, though a simple C option would be sufficient!

**Comment by alonre24** [comment]
Hey, @RMichaelPickering!
I'm glad to share that this vector similarity program is already being used in production with [RediSearch](https://github.com/RediSearch/RediSearch). It's statically linked to the module, and once you launch redis-stack-server, you basically have VectorSimilarity functionality built in. All you have to do is follow RediSearch's [documentation](https://redis.io/docs/interact/search-and-query/search/vectors/) of how to index and query VECTOR data type, and you're good to go :)

**Comment by RMichaelPickering** [comment]
That's great, @alonre24 !!

Can you please point me to the documentation for a C or C++ client library or SDK to access this functionality?

**Comment by alonre24** [comment]
Sure there are many C/C++ clients for redis, you can see some of them here - https://redis.io/resources/clients/#c

**Comment by RMichaelPickering** [comment]
Right, but which of them support RediSearch and, especially, VectorSimilarity? How do I call a similarity search API and pass in a query vector from C or C++?

**Comment by alonre24** [comment]
Here is a basic example of how to run VectorSimilarity queries using the minimal C client [hiredis](https://github.com/redis/hiredis):

```#include <stdio.h>
#include "hiredis.h"

int main(int argc, char **argv)
{
	redisContext *ctx = redisConnect("127.0.0.1", 6379);
	if (ctx == NULL || ctx->err) {
		printf("Connection failed\n");
		return -1;
	}

	redisReply *reply = redisCommand(ctx, "FLUSHALL");
	if (reply == NULL) {
		printf("Command failed (%d): %s\n", ctx->err, ctx->errstr);
		return -1;
	}
	else {
		printf("Command succeeded! Starting from fresh\n");
	}
	freeReplyObject(reply);

	printf("Creating vector index\n");
	size_t dim = 4;
	reply = redisCommand(ctx, "FT.CREATE idx SCHEMA vector VECTOR FLAT 6 DIM %d DISTANCE_METRIC L2 TYPE FLOAT32", dim);
	printf("reply: %s\n", reply->str);
	freeReplyObject(reply);

	// Insert 5 vectors to the index.
	size_t blob_len = dim*sizeof(float);  // each vector is 4 floats.
	for (size_t i = 0; i < 5; i++) {
		float vec[4] = {i, i, i, i};
		reply = redisCommand(ctx, "HSET doc%d vector %b", i, vec, blob_len);
		if (reply == NULL) {
			printf("Command failed (%d): %s\n", ctx->err, ctx->errstr);
			return -1;
		}
		freeReplyObject(reply);
	}
	printf("Added 5 vectors to the vector index\n");
	printf("Running a KNN query:\n");
	float query_vec[4] = {2, 2, 2, 2};
	const char *query_string = "*=>[KNN 3 @vector $blob AS score]";
	reply = redisCommand(ctx, "ft.search idx %s SORTBY score"
							  " PARAMS 2 blob %b DIALECT 2 RETURN 1 score",query_string, query_vec, blob_len);
	if (reply == NULL) {
		printf("Command failed (%d): %s\n", ctx->err, ctx->errstr);
		return -1;
	}
	printf("results:\n");
	for (size_t i = 0; i < reply->elements; i++) {
		if (reply->element[i]->type == REDIS_REPLY_ARRAY) {
			for (size_t j = 0; j < reply->element[i]->elements; j++) {
				printf("   %s\n", reply->element[i]->element[j]->str);
			}
		} else if (reply->element[i]->type == REDIS_REPLY_INTEGER) {
			printf("%lld\n", reply->element[i]->integer);
		} else {
			// reply is a string
			printf("%s\n", reply->element[i]->str);
		}
	}
	freeReplyObject(reply);
	redisFree(ctx);
	printf("Done!\n");

	return 1;
}
```
This will work assuming that you have **redis-stack-server** running locally that listens on port 6379.
Basically, this client just wraps the raw redis commands (in this case, commands that are used to index and query vectors). All the commands in the following examples are explained thoroughly in [RediSearch docs ](https://redis.io/docs/interact/search-and-query/search/vectors/)

**Comment by RMichaelPickering** [comment]
Thanks, that example is very helpful!!
